# General Numpy

In [3]:
import numpy as np

In [ ]:
#### Arrays in Numpy
- Homogeneous - array has to only contain one data type 
- All elements of array MUST be the same data type
- The shape must be rectangula

In [ ]:
#single dimentinal array 
a = np.array([1,2,3,4,5,6,7])

print(a)

[1 2 3 4 5 6 7]


In [6]:
a[-1 : 0 : 1]

array([], dtype=int64)

In [15]:
# All rows now have 4 elements
multiDimArr = np.array([[1, 2, 3, 4], [5, 6, 7, 0], [8, 9, 10, 11]])
print(multiDimArr)

[[ 1  2  3  4]
 [ 5  6  7  0]
 [ 8  9 10 11]]


In [ ]:
# ** differnt from list
multiDimArr[2, 2]

np.int64(10)

In [14]:
a.dtype

dtype('int64')